# Exercise the production cleanup helper with a nested RomFS asset owner.
include("${CMAKE_CURRENT_LIST_DIR}/../../CMake/functions/trim_retired_files.cmake")
if(NOT DEFINED TEST_DIRECTORY)
  message(FATAL_ERROR "Set TEST_DIRECTORY to a disposable test directory")
endif()
if(EXISTS "${TEST_DIRECTORY}")
  message(FATAL_ERROR "Test directory already exists: ${TEST_DIRECTORY}")
endif()
file(MAKE_DIRECTORY "${TEST_DIRECTORY}/mods/hf/lua" "${TEST_DIRECTORY}/modules")
foreach(path core.txt obsolete.txt mods/hf/manifest.ini mods/hf/lua/init.lua mods/hf/obsolete.txt modules/obsolete.txt)
  file(WRITE "${TEST_DIRECTORY}/${path}" "fixture:${path}")
endforeach()
# Reproduce copying Hellfire first, then trimming the parent asset directory.
trim_retired_files("${TEST_DIRECTORY}" "core.txt" "${TEST_DIRECTORY}/root.rm" mods)
foreach(path core.txt mods/hf/manifest.ini mods/hf/lua/init.lua mods/hf/obsolete.txt)
  if(NOT EXISTS "${TEST_DIRECTORY}/${path}")
    message(FATAL_ERROR "Parent cleanup removed ${path}")
  endif()
endforeach()
foreach(path obsolete.txt modules/obsolete.txt)
  if(EXISTS "${TEST_DIRECTORY}/${path}")
    message(FATAL_ERROR "Parent cleanup retained obsolete asset ${path}")
  endif()
endforeach()
# The mod still removes its own retired assets; legacy three-argument calls work.
trim_retired_files("${TEST_DIRECTORY}/mods/hf" "manifest.ini;lua/init.lua" "${TEST_DIRECTORY}/mod.rm")
if(EXISTS "${TEST_DIRECTORY}/mods/hf/obsolete.txt")
  message(FATAL_ERROR "Mod cleanup retained its obsolete asset")
endif()
foreach(path mods/hf/manifest.ini mods/hf/lua/init.lua)
  if(NOT EXISTS "${TEST_DIRECTORY}/${path}")
    message(FATAL_ERROR "Mod cleanup removed a current asset ${path}")
  endif()
endforeach()
file(REMOVE_RECURSE "${TEST_DIRECTORY}")
message(STATUS "Nested asset cleanup regression passed")
